// ordem alfabética

module.exports = {
    AddReactions: "adicionar reações",
    Administrator: "administrador",
    AttachFiles: "anexar arquivos",
    BanMembers: "banir membros",
    ChangeNickname: "mudar nickname",
    Connect: "conectar",
    CreateInstantInvite: "criar convite de instante",
    CreatePrivateThreads: "criar tópicos privados",
    CreatePublicThreads: "criar tópicos públicos",
    DeafenMembers: "ensurdecer membros",
    EmbedLinks: "links incorporados",
    KickMembers: "expulsar members",
    ManageChannels: "gerenciar canais",
    ManageEmojisAndStickers: "gerenciar emojis e stickers",
    ManageEvents: "gerenciar eventos",
    ManageGuild: "gerenciar servidor",
    ManageMessages: "gerenciar mensagens",
    ManageNicknames: "gerenciar nicknames",
    ManageRoles: "gerenciar cargos",
    ManageThreads: "gerenciar tópicos",
    ManageWebhooks: "gerenciar webhooks",
    MentionEveryone: "mencionar everyone",
    ModerateMembers: "moderar membros",
    MoveMembers: "mover membros",
    MuteMembers: "mutar membros",
    PrioritySpeaker: "orador prioritário",
    ReadMessageHistory: "ler histórico de mensagens",
    RequestToSpeak: "pedir para falar",
    SendMessages: "mandar mensagens",
    SendMessagesInThreads: "mandar mensagens em tópicos",
    SendTTSMessages: "mandar mensagens tts",
    Speak: "falar",
    Stream: "vídeo",
    UseApplicationCommands: "usar comandos de aplicativo",
    UseEmbeddedActivities: "usar atividades incorporadas",
    UseExternalEmojis: "usar emojis externos",
    UseExternalStickers: "usar stickers externos",
    UseVAD: "usar atividade de voz",
    ViewAuditLog: "ver log de auditoria",
    ViewChannel: "ver canal",
    ViewGuildInsights: "ver insights do servidor"
};